// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
		int numOfTests = Integer.parseInt(args[0]);

		int numOfSmall = 0;
		for (int i = 0; i < numOfTests; i++) {
			if(Math.random() <= 0.5) {
				numOfSmall++;
			}
		}
		int numOfLarge = numOfTests - numOfSmall;
		System.out.println("> 0.5: " + numOfLarge + " times");
		System.out.println("<= 0.5: " + numOfSmall + " times");
		if (numOfSmall != 0) {
			System.out.println("Ratio: " + (double)numOfLarge / numOfSmall);
		}

	}
}
